### ISSUE TITLE
Add support for Client TLS Certificate Chain

### ISSUE THREAD

**Issue by agluck28** [LabVIEW-Open-Source/MQTT-Connection-SecuredTCP#1]
To support MQTT brokers that do client verification, need to add a way to reference the client certificate and key when making a connection.

**Comment by francois-normandin** [comment]
@agluck28 Thanks for this request.
And looking forward to see your code in that PR on MQTT Broker/Client repo.

**Comment by agluck28** [comment]
@francois-normandin I have some code ready to push, but don't appear to have the ability to create a new branch to push it to. Would you be able to grant me access to create a branch and push to it? Open to other ways as well.

**Comment by francois-normandin** [comment]
@agluck28 You need to create a Pull Request. I will then be able to redirect it to any branch. I understand the code is in LV2020 (TLS support) but the rest of the repo is LV2013,.. so I'll make it available to other developers aside from "main".

If you have not, Fork the repo into your profile and commit your code there. Then you can create a Pull request from your own repo into the LVOS one. Do let me know if your have problems with this.

**Comment by agluck28** [comment]
@francois-normandin A little confused on that workflow. I have only checked out this repo, not the rest of the repos as part of LVOS. Are you saying once I fork this repo, to open a PR on that and you are then able to grab that to be merged in here?

**Comment by francois-normandin** [comment]
Yes, this is the typical Git Workflow.

https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by francois-normandin** [comment]
**For Documentation purpose:**

1. 
![image](https://user-images.githubusercontent.com/11728548/149406719-8a5d0aa5-28db-407d-aa6b-9409f9e24764.png)

2.
![image](https://user-images.githubusercontent.com/11728548/149406758-04a766d8-607b-48a2-9d45-970f5d98db67.png)

3. 
![image](https://user-images.githubusercontent.com/11728548/149406937-068f50be-c579-480e-801c-225f7a21cd83.png)

4.
![image](https://user-images.githubusercontent.com/11728548/149406967-5e718677-c689-4f00-be09-97f181e8958d.png)

5.
![image](https://user-images.githubusercontent.com/11728548/149407171-743b55a0-3902-4280-afa7-d67af1641b69.png)

**Comment by agluck28** [comment]
Thanks for the link, first time doing this on Github and with forks. Typically have just done the branching on the repo and then opening a PR. Believe I got the PR opened correctly, but let me know if there are any issues.

**Comment by francois-normandin** [comment]
@agluck28 I've tested your implementation with a remote server (AWS) and confirm it works.
I`ll be adding the "server" part so that we can support this feature with a LabVIEW-native MQTT Broker as well. Basically, I need the ability to add Trusted certificates so the LV broker can trust the client. (public keys)

Once done, it will be released.
Thanks for your contribution!

**Comment by francois-normandin** [comment]
@agluck28 
I've just released version 3.2.0 with your changes.
I've modified the connector pane of the client key-cert method. I've also refactored the private data to reuse some fields between client and server + added trusted certificates for the broker side of the app.

Thanks a lot.

https://github.com/LabVIEW-Open-Source/MQTT-Connection-SecuredTCP/releases/tag/3.2.0

PS. Should be on VIPM shortly.
There is a dependency on MQTT Connection that is also pending publication on vipm.io
If you need the dependency to test right away, please download this one as well: 
https://github.com/LabVIEW-Open-Source/MQTT-Connection/releases
